compatibility_date = "2022-07-27"
type = "javascript"
main = "dist/index.mjs"
name = "cloudly-storage-test-worker"
account_id = "f86ca9874dda1e291a86b8c1c48186e2"
zone_id = "55e42f9e4cf20c081726c799a7a41f22"
workers_dev = true
routes = ["https://example.com/item*"]

kv_namespaces = [
  { binding = "archive", id = "429fa89f123548ddaf4fba0591b367e8", preview_id = "429fa89f123548ddaf4fba0591b367e8" },
	{ binding = "kvStore", id = "429fa89f123548ddaf4fba0591b367e8", preview_id = "429fa89f123548ddaf4fba0591b367e8" },
]

vars = { }

[build]
command = "npm install && npm run build"

[durable_objects]
bindings = [
	{ name = "DatabaseBuffer", class_name = "Backend" },
	{ name = "Do", class_name = "Do" },
]

[miniflare]
kv_persist = true
cache_persist = true
durable_objects_persist = true


[build.upload]
format = "modules"

[dev]
port = 7212

[env.development]
workers_dev = true
account_id = "f86ca9874dda1e291a86b8c1c48186e2"
kv_namespaces = [
  { binding = "archive", id = "429fa89f123548ddaf4fba0591b367e8", preview_id = "429fa89f123548ddaf4fba0591b367e8" },
]

[env.development.durable_objects]
bindings = [
	{ name = "DatabaseBuffer", class_name = "Backend" },
	{ name = "Do", class_name = "Do" },
]
