compatibility_date = "2022-07-27"
type = "javascript"
name = "cloudly-storage-test-worker"
account_id = "abcdefg01234567890"
zone_id = "abcdefg01234567890"
workers_dev = true
routes = ["https://example.com/item*"]
kv_namespaces = [
  { binding = "kvStore", id = "<ignored>", preview_id = "<ignored>" }
]
vars = { }

[build]
command = "npm install && npm run build"

[durable_objects]
bindings = [
	{ name = "Do", class_name = "Do" }
]


[build.upload]
format = "modules"
main = "./_worker.js"

[dev]
	port = 8999

