name: "Bump"

on:
  push:
    branches:
      - "master"
jobs:
  bump-version:
    name: "Bump version on master"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci: version bump to ')"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
      - name: "Setup Node"
        uses: "actions/setup-node@v3"
        with:
          node-version: current
          cache: 'npm'
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: node_modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: "Version Bump"
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: 'release-'
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
